kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bob-pod-creator
  namespace: 
subjects:
- kind: User
  name: bob
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pod-creator
  apiGroup: rbac.authorization.k8s.io

