kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-creator
  namespace: 
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["*"]

